### ISSUE TITLE
Build error NoSuchFieldError: Companion

### ISSUE THREAD

**Issue by misrakli** [vanniktech/lint-rules#172]
Hi, 
first of all thank you for sharing this work.

When I try to build this project I am currently facing following error:

**Could not load custom lint check jar file /home/user/projects/github/lint-rules/lint-rules-android/build/intermediates/lint/lint.jar
java.lang.NoSuchFieldError: Companion
	at com.vanniktech.lintrules.android.InvalidImportDetectorKt.<clinit>(InvalidImportDetector.kt:15)**
	at com.vanniktech.lintrules.android.IssueRegistry.getIssues(IssueRegistry.kt:18)
	at com.android.tools.lint.client.api.JarFileIssueRegistry.<init>(JarFileIssueRegistry.kt:53)
	at com.android.tools.lint.client.api.JarFileIssueRegistry.<init>(JarFileIssueRegistry.kt:45)
	at com.android.tools.lint.client.api.JarFileIssueRegistry$Factory.get(JarFileIssueRegistry.kt:176)
	at com.android.tools.lint.client.api.JarFileIssueRegistry$Factory.get(JarFileIssueRegistry.kt:143)
	at com.android.tools.lint.client.api.LintDriver.registerCustomDetectors(LintDriver.kt:426)
	at com.android.tools.lint.client.api.LintDriver.analyze(LintDriver.kt:357)
	at com.android.tools.lint.LintCliClient.run(LintCliClient.java:155)
	at com.android.build.gradle.internal.LintGradleClient.run(LintGradleClient.java:197)
....

I am currently working on an own library where I am getting the same error.
Do you have any explanations for that?

working environment: AndroidStudio 3.0.1

Thanks in advance.

**Comment by vanniktech** [comment]
Latest master requires AGP 3.1
Version 0.6.0 works with AGP 3.0

**Comment by misrakli** [comment]
Sorry, but I can't follow your answer.
I tried to build your latest master (cloned yesterday) without touching anything and facing the error described above and I have seen you are using the android gradle plugin 3.0.1.
You didn't just had the time to upgrade or am I missing something?

**Comment by vanniktech** [comment]
For master you need 3.1
